# Generated by Django 6.1.1 on 2026-09-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube')], max_length=32)),
                ('platform_id', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'platform_id'), name='unique_channel_per_platform')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube')], max_length=32)),
                ('platform_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2048)),
                ('source_url', models.URLField(max_length=2048)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('platform_metadata', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('playback_path', models.CharField(blank=True, max_length=1024)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('container', models.CharField(blank=True, max_length=32)),
                ('video_codec', models.CharField(blank=True, max_length=64)),
                ('audio_codec', models.CharField(blank=True, max_length=64)),
                ('resolution', models.CharField(blank=True, max_length=32)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('source_metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('local_status', models.CharField(choices=[('absent', 'Assente'), ('available', 'Disponibile'), ('missing', 'Mancante')], default='absent', max_length=16)),
                ('source_status', models.CharField(choices=[('unknown', 'Sconosciuto'), ('available', 'Disponibile'), ('unavailable', 'Non disponibile'), ('deleted', 'Eliminato')], default='unknown', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.channel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'In coda'), ('downloading', 'In download'), ('processing', 'In elaborazione'), ('completed', 'Completato'), ('failed', 'Non riuscito'), ('cancelled', 'Annullato')], default='queued', max_length=16)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('downloaded_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('eta', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('target_path', models.CharField(blank=True, max_length=1024)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='core.video')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('platform', 'platform_id'), name='unique_video_per_platform'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['status', 'created_at'], name='core_downlo_status_e297d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='download',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'downloading', 'processing'))), fields=('video',), name='one_active_download_per_video'),
        ),
    ]
