# Generated by Django 6.1.1 on 2026-09-25 15:44

from pathlib import PurePosixPath

from django.conf import settings
from django.db import migrations, models


def backfill_thumbnails(apps, schema_editor):
    """Register the .webp sidecar already promoted next to archived videos."""
    Video = apps.get_model("core", "Video")
    root = settings.VHS_MEDIA_ROOT
    for video in Video.objects.exclude(file_path="").filter(thumbnail_path=""):
        thumbnail = PurePosixPath(video.file_path).with_suffix(".webp")
        path = root.joinpath(*thumbnail.parts)
        if ".." not in thumbnail.parts and path.is_file() and not path.is_symlink():
            video.thumbnail_path = str(thumbnail)
            video.save(update_fields=["thumbnail_path"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reconcile_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.RunPython(backfill_thumbnails, migrations.RunPython.noop),
    ]
