# Generated by Django 6.1.1 on 2026-09-25 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video_thumbnail_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='media_probe',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='video',
            name='playback_action',
            field=models.CharField(blank=True, choices=[('', 'Non analizzato'), ('native', 'Riproducibile'), ('remux', 'Cambio contenitore'), ('transcode', 'Conversione'), ('unsupported', 'Non supportato')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='video',
            name='playback_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='probed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlaybackPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('remux', 'Cambio contenitore'), ('transcode', 'Conversione')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'In coda'), ('running', 'In corso'), ('completed', 'Completata'), ('failed', 'Non riuscita')], default='queued', max_length=16)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='core.video')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('video',), name='one_active_preparation_per_video')],
            },
        ),
        migrations.CreateModel(
            name='PlaybackProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_seconds', models.FloatField(default=0)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_progress', to='core.video')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'video'), name='one_progress_per_user_video')],
            },
        ),
    ]
