# Generated by Django 6.1.1 on 2026-09-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='recovered_existing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='superseded_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
