# Generated by Django 6.1.1 on 2026-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_storage_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playback_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='download',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='playbackpreparation',
            name='kind',
            field=models.CharField(choices=[('remux', 'Container change'), ('transcode', 'Conversion')], max_length=16),
        ),
        migrations.AlterField(
            model_name='playbackpreparation',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='local_status',
            field=models.CharField(choices=[('absent', 'Absent'), ('available', 'Available'), ('missing', 'Missing')], default='absent', max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='playback_action',
            field=models.CharField(blank=True, choices=[('', 'Not analyzed'), ('native', 'Playable'), ('remux', 'Container change'), ('transcode', 'Conversion'), ('unsupported', 'Unsupported')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('available', 'Available'), ('unavailable', 'Unavailable'), ('deleted', 'Deleted')], default='unknown', max_length=16),
        ),
    ]
