# Generated by Django 6.1.1 on 2026-10-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_downloads_real_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='ytdlp_version',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
