# Generated by Django 6.1.1 on 2026-10-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_download_ytdlp_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='platform',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='video',
            name='platform',
            field=models.CharField(max_length=32),
        ),
    ]
