# Generated by Django 6.1.1 on 2026-10-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_platform_without_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_kind',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='video',
            name='audio_language',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
